In [9]:


x = np.empty([12 * 471, 18 * 9], dtype = float)
y = np.empty([12 * 471, 1], dtype = float)
for month in range(12):
    for day in range(20):
        for hour in range(24):
            if day == 19 and hour > 14:
                continue
            x[month * 471 + day * 24 + hour, :] = month_data[month][:,day * 24 + hour : day * 24 + hour + 9].reshape(1, -1) #vector dim:18*9 (9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9)
            y[month * 471 + day * 24 + hour, 0] = month_data[month][9, day * 24 + hour + 9] #value
print(x)
print(y)
    
    

[[23.  23.  23.  ...  2.1  2.4  0.8]
 [23.  23.  22.  ...  2.4  0.8  0.9]
 [23.  22.  21.  ...  0.8  0.9  1.1]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[ 0.]
 [ 3.]
 [ 4.]
 ...
 [17.]
 [24.]
 [29.]]


In [11]:
#Normalize
mean_x = np.mean(x, axis = 0) #18 * 9 
std_x = np.std(x, axis = 0) #18 * 9 
for i in range(len(x)): #12 * 471
    for j in range(len(x[0])): #18 * 9 
        if std_x[j] != 0:
            x[i][j] = (x[i][j] - mean_x[j]) / std_x[j]
            


In [12]:
import math
x_train_set = x[: math.floor(len(x) * 0.8), :]
y_train_set = y[: math.floor(len(y) * 0.8), :]
x_validation = x[math.floor(len(x) * 0.8): , :]
y_validation = y[math.floor(len(y) * 0.8): , :]
print(x_train_set)
print(y_train_set)
print(x_validation)
print(y_validation)
print(len(x_train_set))
print(len(y_train_set))
print(len(x_validation))
print(len(y_validation))


dim = 18 * 9 + 1
w = np.zeros([dim, 1])
x = np.concatenate((np.ones([12 * 471, 1]), x), axis = 1).astype(float)
learning_rate = 100
iter_time = 1000
adagrad = np.zeros([dim, 1])
eps = 0.0000000001
for t in range(iter_time):
    loss = np.sqrt(np.sum(np.power(np.dot(x, w) - y, 2))/471/12)#rmse
    if(t%100==0):
        print(str(t) + ":" + str(loss))
    gradient = 2 * np.dot(x.transpose(), np.dot(x, w) - y) #dim*1
    adagrad += gradient ** 2
    w = w - learning_rate * gradient / np.sqrt(adagrad + eps)
np.save('weight.npy', w)

[[ 2.19008735  2.20346527  2.2184631  ...  0.74589232  1.11764779
  -0.85521597]
 [ 2.19008735  2.20346527  1.91355309 ...  1.11569788 -0.85578092
  -0.73173138]
 [ 2.19008735  1.90008542  1.60864308 ... -0.85659845 -0.73244163
  -0.48476221]
 ...
 [-1.13168511 -1.13371313 -1.13554703 ...  2.47165161  2.47438003
   1.73796035]
 [-1.13168511 -1.13371313 -1.44045704 ...  2.47165161  1.73434426
   1.24402201]
 [-1.13168511 -1.43709298 -1.44045704 ...  1.73204049  1.24098708
   0.87356825]]
[[ 0.]
 [ 3.]
 [ 4.]
 ...
 [24.]
 [16.]
 [27.]]
[[-1.43366443 -1.43709298 -1.13554703 ...  1.2389664   0.8709692
   0.99705283]
 [-1.43366443 -1.13371313 -1.13554703 ...  0.86916084  0.9943085
   1.86144494]
 [-1.13168511 -1.13371313 -1.13554703 ...  0.99242936  1.85768356
   2.10841411]
 ...
 [ 0.37821146  0.686566    0.99882305 ... -0.48679288 -0.11574516
  -0.23779304]
 [ 0.68019078  0.98994586  0.69391304 ... -0.11698732 -0.23908445
   0.13266072]
 [ 0.98217009  0.686566    0.38900303 ... -0.2402558

In [13]:
testdata = pd.read_csv('/Users/alston/Documents/ML/test.csv', header = None, encoding = 'big5')
test_data = testdata.iloc[:, 2:]
test_data[test_data == 'NR'] = 0
test_data = test_data.to_numpy()
test_x = np.empty([240, 18*9], dtype = float)
for i in range(240):
    test_x[i, :] = test_data[18 * i: 18* (i + 1), :].reshape(1, -1)
for i in range(len(test_x)):
    for j in range(len(test_x[0])):
        if std_x[j] != 0:
            test_x[i][j] = (test_x[i][j] - mean_x[j]) / std_x[j]
test_x = np.concatenate((np.ones([240, 1]), test_x), axis = 1).astype(float)
test_x

w = np.load('weight.npy')
ans_y = np.dot(test_x, w)
ans_y

FileNotFoundError: [Errno 2] File b'/Users/alston/Desktop/test.csv' does not exist: b'/Users/alston/Desktop/test.csv'