# 1.1 numpy array創建


+ array：創建數組
+ dtype：指定數據類型
+ zeros：創建數據全為0
+ ones：創建數據全為1
+ empty：創建數據接近0
+ arrange：按指定範圍創建數據
+ linspace：創建線段

### 指定數據 dtype
+ int
+ int32
+ float
+ float32


In [4]:
import numpy as np

a = np.array([1,2,3], dtype=np.int)
print(a)

[1 2 3]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

print('-'*20)

c = b.reshape((1,6))
print(c)

[[1 2 3]
 [4 5 6]]
--------------------
[[1 2 3 4 5 6]]


In [13]:
zeroArray = np.zeros((3,4), dtype=np.int)
print(zeroArray)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
oneArray = np.ones((3,4), dtype=np.int).reshape(1,12)
print(oneArray)

[[1 1 1 1 1 1 1 1 1 1 1 1]]


In [17]:
emptyArray = np.empty((3,4))
print(emptyArray)

[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


### 用arange創建連續整數： 

* 不包含末位數

In [20]:
arangeArray = np.arange(10, 20, 2)
print(arangeArray)

[10 12 14 16 18]


### 用linspace創建線段型數據：

In [28]:
linArray = np.linspace(10,20,6).reshape((2,3))
print(linArray)

[[10. 12. 14.]
 [16. 18. 20.]]
