# Numpy 索引

In [1]:
import numpy as np

In [4]:
a = np.arange(3,15)
print('a:',a)
print("第三個值為：",a[2])

a: [ 3  4  5  6  7  8  9 10 11 12 13 14]
第三個值為： 5


In [11]:
a = np.arange(3,15).reshape((3,4))
print('a:\n',a)

print('-'*15,'使用index找出值','-'*15)

print("第二列第一行的值為：",a[1][0])

print('-'*15,'相同作法','-'*15)

print("第二列第一行的值為：",a[1,0])
print("第二列的值為：",a[1,:])
print("第二列的第二,三行值為：",a[1,1:3])

a:
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
--------------- 使用index找出值 ---------------
第二列第一行的值為： 7
--------------- 相同作法 ---------------
第二列第一行的值為： 7
第二列的值為： [ 7  8  9 10]
第二列的第二,三行值為： [8 9]


In [18]:
print("逐步將矩陣一列一列印出(預設)：")
for row in a:
    print(row)

逐步將矩陣一列一列印出(預設)：
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [19]:
print("逐步將矩陣一行一行印出：")
for col in a.T:
    print(col)

逐步將矩陣一行一行印出：
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


### flatten(): 回傳一維陣列
### flat: 迭代器

In [21]:
print("逐步將矩陣一個項目一個項目印出：")
for item in a.flat:
    print(item)

逐步將矩陣一個項目一個項目印出：
3
4
5
6
7
8
9
10
11
12
13
14
