# Numpy基礎運算1

* 矩陣相減：-
* 矩陣相加：+
* 矩陣相乘：np.dot()

* 二次方：**2
* 三次方：**3

* sin函數：np.sin()

In [3]:
import numpy as np

In [9]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)

print(a+b)
print(a-b)
print(a.dot(b))


print(a**2)
print(np.sin(a))

[10 21 32 43]
[10 19 28 37]
200
[ 100  400  900 1600]
[-0.54402111  0.91294525 -0.98803162  0.74511316]


## 對矩陣元素

* 求和：np.sum()
* 求最小值：np.min()
* 求最大值：np.max()
* 求平均：np.mean()
* 求中位數：np.median()
* 求最大元素index: np.argmax()
* 求最小元素index: np.argmin()
* 求累加：np.cumsum()
* 求累差：np.diff()
* 求非0元素：np.nonzero()
* 排序：np.sort()
* 矩陣反向：np.transpose(A) / A.T
* 大於某數變某數, 小於某數變某數: np.clip(Array,Array_min,Array_max)

#### 上述方法皆可以指定 
* axis = 0  =>對列
* axis = 1  =>對行

#### 隨機抽取0~1個指定數目
* np.random.random(number)

In [17]:
a = np.random.random(4).reshape(2,2)

In [27]:
print(a)

print('-'*15,'分隔線','-'*15)

print(np.sum(a))
print(np.min(a))
print(np.max(a))

print('-'*15,'分隔線','-'*15)

print(np.sum(a, axis=0))
print(np.min(a, axis=0))
print(np.max(a, axis=0))

[[0.00737646 0.57127136]
 [0.03731283 0.07708265]]
--------------- 分隔線 ---------------
0.6930433040528268
0.007376458183004808
0.5712713627780054
--------------- 分隔線 ---------------
[0.04468929 0.64835401]
[0.00737646 0.07708265]
[0.03731283 0.57127136]


In [65]:
a = np.arange(2,14).reshape((3,4))

print('a:\n',a)

print('-'*15,'分隔線','-'*15)

print('argmin:',np.argmin(a,axis=1))
print('argmax:',np.argmax(a))

print('-'*15,'分隔線','-'*15)

print('mean:',np.mean(a,axis=0))
print('median:',np.median(a,axis=0))

print('-'*15,'分隔線','-'*15)

print('cumsum:',np.cumsum(a))
print('diff:\n',np.diff(a))

print('-'*15,'分隔線','-'*15)

print('nonzero:',np.nonzero(a))
#這個函數將所有非零元素的行與列坐標分割開，重構成兩個分別關於行和列的矩陣。

print('-'*15,'分隔線','-'*15)

b = np.random.random(4).reshape((2,2))
print('b:\n',b)
print('sort:\n',np.sort(b))

print('-'*15,'分隔線','-'*15)

print('a:\n',a)
print('transpose:\n',np.transpose(a))
print('-'*15,'一樣結果','-'*15)
print('transpose:\n',a.T)
print(a.T.dot(a))

print('-'*15,'分隔線','-'*15)

print('clip:\n',np.clip(a,3,5))

a:
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
--------------- 分隔線 ---------------
argmin: [0 0 0]
argmax: 11
--------------- 分隔線 ---------------
mean: [6. 7. 8. 9.]
median: [6. 7. 8. 9.]
--------------- 分隔線 ---------------
cumsum: [ 2  5  9 14 20 27 35 44 54 65 77 90]
diff:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
--------------- 分隔線 ---------------
nonzero: (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
--------------- 分隔線 ---------------
b:
 [[0.15826791 0.16747157]
 [0.15258731 0.05392788]]
sort:
 [[0.15826791 0.16747157]
 [0.05392788 0.15258731]]
--------------- 分隔線 ---------------
a:
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
transpose:
 [[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
--------------- 一樣結果 ---------------
transpose:
 [[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
--------------- 分隔線 ---------------
clip:
 [[3 3 4 5]
 [5 5 5 5]
 [5 5 5 5]]
