In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = np.arange(5)
a.dtype

dtype('int64')

In [5]:
# 從 numpy 轉換到 tensorflow
aa = tf.convert_to_tensor(a)
print(aa)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


In [7]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)
print(aa)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## 資料型態轉換

In [8]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [9]:
tf.cast(aa, dtype=tf.double)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [10]:
tf.cast(aa, dtype=tf.int32)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

### [0, 1]與boolean值轉換

In [13]:
b = tf.constant([0, 1])
b_cast = tf.cast(b, dtype=tf.bool)

In [14]:
b_dcast = tf.cast(b_cast, dtype=tf.bool)

In [15]:
b_dcast

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [24]:
a = tf.ones([3,4])

In [29]:
a.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [33]:
a = "High Performance Computing"

In [34]:
a.lower()

'high performance computing'