# Final Exam: 109356003 資碩一  楊仁瀚

###### 考試注意事項:
1. 考試時間: 9:10 ~ 12:00 
2. 考試開始時 (9:10 a.m.), 我會用 Cisco Webex 口頭講解, 接著在 Q&A 上答問. 
3. 答案卷繳交處: WM5 => 作業管理區 => "Final Exam" 資料夾
4. 每個人只繳交一個答卷檔案, 檔名都稱為: Final Exam.ipynb;
5. 答卷檔案內第一個格子(cell)請改成自己的學號, 系級, 及姓名, 例如: 109350001 會碩一  張大頭
6. 答卷檔案內的程式碼必須執行過並呈現跑出來的結果, 評量時根據程式碼以及跑出來的結果給分

### Files proived:
hopedale.txt


In [1]:
import numpy as np
import pandas as pd

### Problem 1 (5%)

In [82]:
print(np.arange(24).reshape(3,2,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


### Problem 2 (5%)

In [84]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, size=(3, 4)), columns=list('ABCD'))
print(df)
print('-'*20)
print(df.cumprod())

   A  B  C  D
0  5  8  9  5
1  0  0  1  7
2  6  9  2  4
--------------------
   A  B   C    D
0  5  8   9    5
1  0  0   9   35
2  0  0  18  140


### Problem 3 (10%)

In [93]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]]])
print(x.reshape(3,1,3))

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


### Problem 4 (10%)

In [36]:
x = np.array(range(1, 13)).reshape(3, 4) 
print(-1*np.sort(-x[::-1]))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### Problem 5 (10%)

In [85]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, size=(3, 4)), columns=list('ABCD'))
print(df)
print('-'*20)
print(df.max()-df.min())

   A  B  C  D
0  5  8  9  5
1  0  0  1  7
2  6  9  2  4
--------------------
A    6
B    9
C    8
D    3
dtype: int64


### Problem 6 (10%)

In [54]:
np.random.seed(0)
df = pd.DataFrame(np.random.randn(1000, 4), columns=list('ABCD'))
print("The number of negative:",sum(np.sum(df<0)))
print("The number of non-negative:",sum(np.sum(df>=0)))

The number of negative: 2047
The number of non-negative: 1953


### Problem 7 (10%)

In [92]:
with open('hopedale.txt', 'r') as input_file: 
    input = input_file.readlines()

input.reverse() 
input[0]+='\n'
for content in input:
    print(content,end="")

      166
       83
        8
       35
       12
       16
        2
       29
       22
#Table 17, p.265--266
#Source: C. Elton (1942) "Voles, Mice and Lemmings", Oxford Univ. Press
Coloured fox fur production, HOPEDALE, Labrador, 1834-1842


### Problem 8 (20%)

In [75]:
x = np.arange(12).reshape(3,4)

result = []
for i in range(3):
    result.append([x[i][i]])
print(result)

[[0], [5], [10]]


### Problem 9 (20%)

In [77]:
def find_value(inputList):
    
    result = list()
    
    for i in range(len(inputList)):    
        if (i % 2 != 0 or i==(len(inputList)-1)):       
            result.append(inputList[i])
            
    return(result)

In [79]:
print(find_value([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

[1, 3, 5, 7, 9, 10]


In [81]:
print(find_value([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

[1, 3, 5, 7, 9]


# The End!